[theme]
base                     = "light"
primaryColor             = "#4f46e5"
backgroundColor          = "#f8fafc"
secondaryBackgroundColor = "#f0f4ff"
textColor                = "#1e293b"
font                     = "sans serif"

[server]
headless        = true
enableCORS      = false
port            = 8501

[browser]
gatherUsageStats = false
